import { Post } from "@/type";

export const POSTS: Post[] = [
    {
        id: 1,
        category: 'React',
        title: 'Understanding React Hooks',
        image: 'https://example.com/react-hooks.jpg',
        caption: 'A deep dive into the world of React Hooks.',
        date: '2023-06-01',
        minutesToRead: 8,
        author: 'John Doe',
        nbViews: 120,
        nbComments: 45,
        slug: 'understanding-react-hooks'
      },
      {
        id: 2,
        category: 'Next',
        title: 'Getting Started with Next.js',
        image: 'https://example.com/nextjs-start.jpg',
        caption: 'A comprehensive guide to starting your journey with Next.js.',
        date: '2023-06-05',
        minutesToRead: 10,
        author: 'Jane Smith',
        nbViews: 200,
        nbComments: 60,
        slug: 'getting-started-with-nextjs'
      },
      {
        id: 3,
        category: 'CSS',
        title: 'CSS Grid Layout: A Beginner’s Guide',
        image: 'https://example.com/css-grid.jpg',
        caption: 'Learn the basics of CSS Grid Layout.',
        date: '2023-06-10',
        minutesToRead: 7,
        author: 'Emily Johnson',
        nbViews: 150,
        nbComments: 30,
        slug: 'css-grid-layout-beginners-guide'
      },
      {
        id: 4,
        category: 'React Native',
        title: 'Building Mobile Apps with React Native',
        image: 'https://example.com/react-native.jpg',
        caption: 'An introduction to mobile app development with React Native.',
        date: '2023-06-15',
        minutesToRead: 12,
        author: 'Michael Brown',
        nbViews: 180,
        nbComments: 55,
        slug: 'building-mobile-apps-with-react-native'
      },
      {
        id: 5,
        category: 'JavaScript',
        title: 'JavaScript ES6 Features You Should Know',
        image: 'https://example.com/js-es6.jpg',
        caption: 'Explore the essential features introduced in JavaScript ES6.',
        date: '2023-06-20',
        minutesToRead: 9,
        author: 'Sarah Wilson',
        nbViews: 220,
        nbComments: 75,
        slug: 'javascript-es6-features-you-should-know'
      },
      {
        id: 6,
        category: 'React',
        title: 'State Management in React with Redux',
        image: 'https://example.com/react-redux.jpg',
        caption: 'Master state management in React using Redux.',
        date: '2023-06-25',
        minutesToRead: 11,
        author: 'David Martinez',
        nbViews: 190,
        nbComments: 50,
        slug: 'state-management-in-react-with-redux'
      },
      {
        id: 7,
        category: 'Next',
        title: 'Next.js API Routes: A Complete Guide',
        image: 'https://example.com/nextjs-api.jpg',
        caption: 'Learn how to create API routes in Next.js.',
        date: '2023-06-30',
        minutesToRead: 8,
        author: 'Laura Davis',
        nbViews: 170,
        nbComments: 40,
        slug: 'nextjs-api-routes-complete-guide'
      },
      {
        id: 8,
        category: 'CSS',
        title: 'Flexbox vs. Grid: Which One Should You Use?',
        image: 'https://example.com/flexbox-grid.jpg',
        caption: 'A comparison of CSS Flexbox and Grid Layout.',
        date: '2023-07-05',
        minutesToRead: 10,
        author: 'Chris Moore',
        nbViews: 140,
        nbComments: 35,
        slug: 'flexbox-vs-grid-which-one-should-you-use'
      },
      {
        id: 9,
        category: 'React Native',
        title: 'Animations in React Native: A Practical Guide',
        image: 'https://example.com/react-native-animations.jpg',
        caption: 'Create smooth animations in your React Native apps.',
        date: '2023-07-10',
        minutesToRead: 9,
        author: 'Sophia Anderson',
        nbViews: 160,
        nbComments: 45,
        slug: 'animations-in-react-native-practical-guide'
      },
      {
        id: 10,
        category: 'JavaScript',
        title: 'Asynchronous JavaScript: Promises, Async/Await',
        image: 'https://example.com/js-async.jpg',
        caption: 'Master asynchronous programming in JavaScript with Promises and Async/Await.',
        date: '2023-07-15',
        minutesToRead: 12,
        author: 'James Thompson',
        nbViews: 250,
        nbComments: 80,
        slug: 'asynchronous-javascript-promises-async-await'
      }
]